In [5]:
import numpy as np
from pylanczos import PyLanczos


def exec_sample():
    matrix = np.diag([float(i) for i in range(1, 11)])
    print(matrix)

    engine = PyLanczos(matrix, True, 5)  # Find 2 maximum eigenpairs
    eigenvalues, eigenvectors = engine.run()
    print("Eigenvalue: {}".format(eigenvalues))
    print("Eigenvector:")
    print(eigenvectors)


if __name__ == "__main__":
    exec_sample()

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  4.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  5.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  6.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  7.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  8.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]]
Eigenvalue: [10.  9.  8.  7.  6.]
Eigenvector:
[[ 9.71445147e-17  5.55111512e-17 -6.93889390e-17  1.04083409e-17
  -1.38777878e-17]
 [ 3.12250226e-17 -5.55111512e-17 -1.87350135e-16 -8.67361738e-18
   2.28983499e-16]
 [ 2.08166817e-17 -4.02455846e-16 -2.35922393e-16  4.51028104e-17
  -5.55111512e-17]
 [ 1.35308431e-16 -2.77555756e-17 -1.04083409e-16  2.60208521e-17
  -1.52655666e-16]
 [-7.37257477e-17  1.59594560e-16 -4.19803081e-16  6.93889390e-18
   6.10622664e-16]
 [-2.02095285e-16 -2.04697370e-16  2.91433544e-16  2.48932819e-16
  -1.00000000e+00]
 [-7.7303614